// GENERATED — mirror of data/costs.json (hand-edit BOTH or re-run the pipeline)
window.COSTS = {
  "_note": "GENERATED by costs/build-costs.ps1 - do not hand-edit. items: processing fee per BATCH, indexed by refinement path (matches recipe inputs_alternatives[N]); null = that path is not priced yet; uc = fee for one batch, y = units it yields. The fee EXCLUDES the inputs. materials: per-UNIT cost of a raw material, added on top of the fees.",
  "_generated": "2026-08-02",
  "materials": {
    "anthracite": 66,
    "bauxite": 81,
    "beryllium": 63,
    "caoutchouc": 42,
    "Chemical Substances": 36,
    "chrome": 84,
    "coal": 42,
    "cobalt": 102,
    "copper": 81,
    "diamonds": 171,
    "gold": 150,
    "iridium": 150,
    "iron": 69,
    "manganese": 96,
    "mineral oil": 66,
    "nickel": 88,
    "organic material": 57,
    "plasma": 132,
    "platinum": 150,
    "silicon": 42,
    "silver": 73,
    "solid carbonite shell": 36,
    "titanium": 147,
    "vanadium": 102,
    "water": 21
  },
  "items": {
    "Advanced Civilian Arm Pads": [
      {
        "uc": 371,
        "y": 3
      }
    ],
    "Advanced Civilian Helmet": [
      {
        "uc": 714,
        "y": 3
      }
    ],
    "Advanced Civilian Leg Pads": [
      {
        "uc": 371,
        "y": 3
      }
    ],
    "Advanced Civilian Shoulder Pads": [
      {
        "uc": 371,
        "y": 3
      }
    ],
    "Advanced Civilian Torso Armor": [
      {
        "uc": 740,
        "y": 3
      }
    ],
    "aluminum": [
      {
        "uc": 198,
        "y": 1
      }
    ],
    "Aquatican Brew": [
      {
        "uc": 61,
        "y": 5
      }
    ],
    "Aramid Altered Arm Pads": [
      {
        "uc": 377,
        "y": 3
      }
    ],
    "Aramid Altered Helmet": [
      {
        "uc": 833,
        "y": 3
      }
    ],
    "Aramid Altered Shoulder Pads": [
      {
        "uc": 377,
        "y": 3
      }
    ],
    "Aramid Altered Torso Armor": [
      {
        "uc": 861,
        "y": 3
      }
    ],
    "Aramid Basic Arm Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "Aramid Basic Gloves": [
      {
        "uc": 194,
        "y": 3
      }
    ],
    "Aramid Basic Helmet": [
      {
        "uc": 868,
        "y": 3
      }
    ],
    "Aramid Basic Leg Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "Aramid Basic Shoulder Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "Aramid Basic Torso Armor": [
      {
        "uc": 866,
        "y": 3
      }
    ],
    "Aramid Modified Arm Pads": [
      {
        "uc": 373,
        "y": 3
      }
    ],
    "Aramid Modified Gloves": [
      {
        "uc": 208,
        "y": 3
      }
    ],
    "Aramid Modified Helmet": [
      {
        "uc": 833,
        "y": 3
      }
    ],
    "Aramid Modified Leg Pads": [
      {
        "uc": 373,
        "y": 3
      }
    ],
    "Aramid Modified Shoulder Pads": [
      {
        "uc": 373,
        "y": 3
      }
    ],
    "Aramid Modified Torso Armor": [
      {
        "uc": 859,
        "y": 3
      }
    ],
    "Aramid Altered Leg Pads": [
      {
        "uc": 377,
        "y": 3
      }
    ],
    "Armalite Survival": [
      {
        "uc": 1822,
        "y": 1
      },
      {
        "uc": 1766,
        "y": 1
      }
    ],
    "Aurelian Technologies Bio Rounds": [
      {
        "uc": 164,
        "y": 4
      }
    ],
    "Aurelian Technologies Dominator": [
      {
        "uc": 3252,
        "y": 1
      },
      {
        "uc": 3233,
        "y": 1
      }
    ],
    "Barracuda Rounds": [
      {
        "uc": 105,
        "y": 4
      }
    ],
    "Battle MediKit": [
      {
        "uc": 119,
        "y": 3
      }
    ],
    "Biocell": [
      {
        "uc": 162,
        "y": 3
      }
    ],
    "bioplasma": [
      {
        "uc": 93,
        "y": 1
      }
    ],
    "carbon": [
      {
        "uc": 168,
        "y": 1
      },
      {
        "uc": 162,
        "y": 1
      },
      {
        "uc": 168,
        "y": 1
      }
    ],
    "carbon fiber": [
      {
        "uc": 368,
        "y": 1
      }
    ],
    "chemicals": [
      {
        "uc": 72,
        "y": 1
      }
    ],
    "Chrono Enervon Energy Cell": [
      {
        "uc": 137,
        "y": 4
      }
    ],
    "Chrono Enervon Pistol EP24": [
      {
        "uc": 1930,
        "y": 1
      },
      {
        "uc": 1910,
        "y": 1
      }
    ],
    "conductor": [
      {
        "uc": 117,
        "y": 1
      }
    ],
    "cpu": [
      {
        "uc": 276,
        "y": 1
      }
    ],
    "CryoTech CM2 Healing Cell": [
      {
        "uc": 71,
        "y": 4
      }
    ],
    "CryoTech Healing Cell": [
      {
        "uc": 170,
        "y": 4
      }
    ],
    "CryoTech Medigun CM1": [
      {
        "uc": 3285,
        "y": 1
      },
      {
        "uc": 3229,
        "y": 1
      },
      {
        "uc": 3265,
        "y": 1
      }
    ],
    "CryoTech Medigun CM2": [
      {
        "uc": 3228,
        "y": 1
      },
      {
        "uc": 3247,
        "y": 1
      }
    ],
    "Delta Powered Arm Pads": [
      {
        "uc": 377,
        "y": 3
      }
    ],
    "Delta Powered Gloves": [
      {
        "uc": 198,
        "y": 3
      }
    ],
    "Delta Powered Helmet": [
      {
        "uc": 833,
        "y": 3
      }
    ],
    "Delta Powered Leg Pads": [
      {
        "uc": 377,
        "y": 3
      }
    ],
    "Delta Powered Shoulder Pads": [
      {
        "uc": 377,
        "y": 3
      }
    ],
    "Delta Powered Torso Armor": [
      {
        "uc": 859,
        "y": 3
      }
    ],
    "Detox Combat Arm Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "Detox Combat Gloves": [
      {
        "uc": 194,
        "y": 3
      }
    ],
    "Detox Combat Helmet": [
      {
        "uc": 868,
        "y": 3
      }
    ],
    "Detox Combat Leg Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "Detox Combat Shoulder Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "Detox Combat Torso Armor": [
      {
        "uc": 866,
        "y": 3
      }
    ],
    "Dice": [
      {
        "uc": 440,
        "y": 1
      }
    ],
    "Dilatant 46b Arm Pads": [
      {
        "uc": 377,
        "y": 3
      }
    ],
    "Dilatant 46b Gloves": [
      {
        "uc": 198,
        "y": 3
      }
    ],
    "Dilatant 46b Helmet": [
      {
        "uc": 833,
        "y": 3
      }
    ],
    "Dilatant 46b Leg Pads": [
      {
        "uc": 377,
        "y": 3
      }
    ],
    "Dilatant 46b Shoulder Pads": [
      {
        "uc": 377,
        "y": 3
      }
    ],
    "Dilatant 46b Torso Armor": [
      {
        "uc": 859,
        "y": 3
      }
    ],
    "Dilatant 50b Arm Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "Dilatant 50b Gloves": [
      {
        "uc": 197,
        "y": 3
      }
    ],
    "Dilatant 50b Helmet": [
      {
        "uc": 860,
        "y": 3
      }
    ],
    "Dilatant 50b Leg Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "Dilatant 50b Shoulder Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "Dilatant 50b Torso Armor": [
      {
        "uc": 861,
        "y": 3
      }
    ],
    "DOA 187": [
      {
        "uc": 4361,
        "y": 1
      },
      {
        "uc": 4345,
        "y": 1
      },
      {
        "uc": 4317,
        "y": 1
      }
    ],
    "DOA187 Energy Cell": [
      {
        "uc": 137,
        "y": 4
      }
    ],
    "DoubleCheese Mystique": [
      {
        "uc": 64,
        "y": 5
      }
    ],
    "electronic component": [
      {
        "uc": 599,
        "y": 1
      }
    ],
    "Emergency MediKit": [
      {
        "uc": 163,
        "y": 3
      }
    ],
    "EMP-Rv3": [
      {
        "uc": 502,
        "y": 5
      },
      {
        "uc": 509,
        "y": 5
      }
    ],
    "Enfield Energy Cell": [
      {
        "uc": 170,
        "y": 4
      }
    ],
    "Enfield Incapacitator Rifle ER-X": [
      {
        "uc": 3191,
        "y": 1
      },
      {
        "uc": 3150,
        "y": 1
      }
    ],
    "Enfield Life Protector": [
      {
        "uc": 1831,
        "y": 1
      },
      {
        "uc": 1866,
        "y": 1
      }
    ],
    "Envirotech Gloves": [
      {
        "uc": 182,
        "y": 3
      }
    ],
    "FGz-78": [
      {
        "uc": 203,
        "y": 5
      }
    ],
    "Firstborn Powered Arm Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "Firstborn Powered Gloves": [
      {
        "uc": 197,
        "y": 3
      }
    ],
    "Firstborn Powered Helmet": [
      {
        "uc": 860,
        "y": 3
      }
    ],
    "Firstborn Powered Leg Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "Firstborn Powered Shoulder Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "Firstborn Powered Torso Armor": [
      {
        "uc": 861,
        "y": 3
      }
    ],
    "Flying Orange": [
      {
        "uc": 61,
        "y": 5
      }
    ],
    "Gakk MG6": [
      {
        "uc": 2540,
        "y": 1
      },
      {
        "uc": 2608,
        "y": 1
      },
      {
        "uc": 2596,
        "y": 1
      }
    ],
    "Gakk MG6 Rounds": [
      {
        "uc": 61,
        "y": 4
      }
    ],
    "Ginnan Sushi": [
      {
        "uc": 61,
        "y": 5
      }
    ],
    "glass": [
      {
        "uc": 132,
        "y": 3
      }
    ],
    "hacking interface": [
      {
        "uc": 290,
        "y": 3
      }
    ],
    "hallem tar7 rounds": [
      {
        "uc": 180,
        "y": 4
      }
    ],
    "Hallem TAR7 Tactical Assault Rifle": [
      {
        "uc": 4997,
        "y": 1
      }
    ],
    "Havoc Powered Arm Pads": [
      {
        "uc": 373,
        "y": 3
      }
    ],
    "Havoc Powered Gloves": [
      {
        "uc": 208,
        "y": 3
      }
    ],
    "Havoc Powered Helmet": [
      {
        "uc": 833,
        "y": 3
      }
    ],
    "Havoc Powered Leg Pads": [
      {
        "uc": 373,
        "y": 3
      }
    ],
    "Havoc Powered Shoulder Pads": [
      {
        "uc": 373,
        "y": 3
      }
    ],
    "Havoc Powered Torso Armor": [
      {
        "uc": 859,
        "y": 3
      }
    ],
    "high performance conductor": [
      {
        "uc": 186,
        "y": 1
      },
      {
        "uc": 186,
        "y": 1
      },
      {
        "uc": 186,
        "y": 1
      },
      {
        "uc": 180,
        "y": 1
      },
      {
        "uc": 180,
        "y": 1
      }
    ],
    "HR420": [
      {
        "uc": 1947,
        "y": 1
      },
      {
        "uc": 1883,
        "y": 1
      }
    ],
    "HR420 Energy Cell": [
      {
        "uc": 71,
        "y": 4
      }
    ],
    "Hypobaric Arm Pads": [
      {
        "uc": 377,
        "y": 3
      }
    ],
    "Hypobaric Gloves": [
      {
        "uc": 198,
        "y": 3
      }
    ],
    "Hypobaric Helmet": [
      {
        "uc": 833,
        "y": 3
      }
    ],
    "Hypobaric Leg Pads": [
      {
        "uc": 377,
        "y": 3
      }
    ],
    "Hypobaric Shoulder Pads": [
      {
        "uc": 377,
        "y": 3
      }
    ],
    "Hypobaric Torso Armor": [
      {
        "uc": 859,
        "y": 3
      }
    ],
    "Infensus Essentials Arm Pads": [
      {
        "uc": 373,
        "y": 3
      }
    ],
    "Infensus Essentials Helmet": [
      {
        "uc": 833,
        "y": 3
      }
    ],
    "Infensus Essentials Leg Pads": [
      {
        "uc": 373,
        "y": 3
      }
    ],
    "Infensus Essentials Shoulder Pads": [
      {
        "uc": 373,
        "y": 3
      }
    ],
    "Infensus Essentials Torso Armor": [
      {
        "uc": 866,
        "y": 3
      }
    ],
    "Infensus Heavy Arm Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "Infensus Heavy Gloves": [
      {
        "uc": 194,
        "y": 3
      }
    ],
    "Infensus Heavy Helmet": [
      {
        "uc": 868,
        "y": 3
      }
    ],
    "Infensus Heavy Leg Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "Infensus Heavy Shoulder Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "Infensus Heavy Torso Armor": [
      {
        "uc": 866,
        "y": 3
      }
    ],
    "Infensus Minimalist Arm Pads": [
      {
        "uc": 377,
        "y": 3
      }
    ],
    "Infensus Minimalist Gloves": [
      {
        "uc": 198,
        "y": 3
      }
    ],
    "Infensus Minimalist Helmet": [
      {
        "uc": 833,
        "y": 3
      }
    ],
    "Infensus Minimalist Leg Pads": [
      {
        "uc": 377,
        "y": 3
      }
    ],
    "Infensus Minimalist Shoulder Pads": [
      {
        "uc": 377,
        "y": 3
      }
    ],
    "Infensus Minimalist Torso Armor": [
      {
        "uc": 859,
        "y": 3
      }
    ],
    "Infensus Shock Arm Pads": [
      {
        "uc": 373,
        "y": 3
      }
    ],
    "Infensus Shock Gloves": [
      {
        "uc": 208,
        "y": 3
      }
    ],
    "Infensus Shock Helmet": [
      {
        "uc": 833,
        "y": 3
      }
    ],
    "Infensus Shock Leg Pads": [
      {
        "uc": 373,
        "y": 3
      }
    ],
    "Infensus Shock Shoulder Pads": [
      {
        "uc": 373,
        "y": 3
      }
    ],
    "Infensus Shock Torso Armor": [
      {
        "uc": 859,
        "y": 3
      }
    ],
    "Infensus X1 Assault Arm Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "Infensus X1 Assault Gloves": [
      {
        "uc": 197,
        "y": 3
      }
    ],
    "Infensus X1 Assault Helmet": [
      {
        "uc": 860,
        "y": 3
      }
    ],
    "Infensus X1 Assault Leg Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "Infensus X1 Assault Shoulder Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "Infensus X1 Assault Torso Armor": [
      {
        "uc": 861,
        "y": 3
      }
    ],
    "Infostyle Gloves": [
      {
        "uc": 182,
        "y": 3
      }
    ],
    "Infusion Gloves": [
      {
        "uc": 182,
        "y": 3
      }
    ],
    "Justicar Powered Arm Pads": [
      {
        "uc": 371,
        "y": 3
      }
    ],
    "Justicar Powered Helmet": [
      {
        "uc": 833,
        "y": 3
      }
    ],
    "Justicar Powered Leg Pads": [
      {
        "uc": 371,
        "y": 3
      }
    ],
    "Justicar Powered Shoulder Pads": [
      {
        "uc": 371,
        "y": 3
      }
    ],
    "Justicar Powered Torso Armor": [
      {
        "uc": 861,
        "y": 3
      }
    ],
    "Leech Arm Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "Leech Helmet": [
      {
        "uc": 833,
        "y": 3
      }
    ],
    "Leech Leg Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "Leech Shoulder Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "Leech Torso Armor": [
      {
        "uc": 866,
        "y": 3
      }
    ],
    "Legionnaire Powered Arm Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "Legionnaire Powered Gloves": [
      {
        "uc": 194,
        "y": 3
      }
    ],
    "Legionnaire Powered Helmet": [
      {
        "uc": 868,
        "y": 3
      }
    ],
    "Legionnaire Powered Leg Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "Legionnaire Powered Shoulder Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "Legionnaire Powered Torso Armor": [
      {
        "uc": 866,
        "y": 3
      }
    ],
    "Linner PP7": [
      {
        "uc": 4272,
        "y": 1
      },
      {
        "uc": 4345,
        "y": 1
      },
      {
        "uc": 4311,
        "y": 1
      }
    ],
    "linner pp7 rounds": [
      {
        "uc": 98,
        "y": 4
      }
    ],
    "Locans Defense Arm Pads": [
      {
        "uc": 377,
        "y": 3
      }
    ],
    "Locans Defense Gloves": [
      {
        "uc": 198,
        "y": 3
      }
    ],
    "Locans Defense Helmet": [
      {
        "uc": 833,
        "y": 3
      }
    ],
    "Locans Defense Leg Pads": [
      {
        "uc": 377,
        "y": 3
      }
    ],
    "Locans Defense Shoulder Pads": [
      {
        "uc": 377,
        "y": 3
      }
    ],
    "Locans Defense Torso Armor": [
      {
        "uc": 859,
        "y": 3
      }
    ],
    "Locans Ethereal Arm Pads": [
      {
        "uc": 373,
        "y": 3
      }
    ],
    "Locans Ethereal Gloves": [
      {
        "uc": 208,
        "y": 3
      }
    ],
    "Locans Ethereal Helmet": [
      {
        "uc": 833,
        "y": 3
      }
    ],
    "Locans Ethereal Leg Pads": [
      {
        "uc": 373,
        "y": 3
      }
    ],
    "Locans Ethereal Shoulder Pads": [
      {
        "uc": 373,
        "y": 3
      }
    ],
    "Locans Ethereal Torso Armor": [
      {
        "uc": 859,
        "y": 3
      }
    ],
    "Locans Patrol Arm Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "Locans Patrol Gloves": [
      {
        "uc": 197,
        "y": 3
      }
    ],
    "Locans Patrol Helmet": [
      {
        "uc": 860,
        "y": 3
      }
    ],
    "Locans Patrol Leg Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "Locans Patrol Shoulder Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "Locans Patrol Torso Armor": [
      {
        "uc": 861,
        "y": 3
      }
    ],
    "Locans Pressured Arm Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "Locans Pressured Gloves": [
      {
        "uc": 194,
        "y": 3
      }
    ],
    "Locans Pressured Helmet": [
      {
        "uc": 868,
        "y": 3
      }
    ],
    "Locans Pressured Leg Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "Locans Pressured Shoulder Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "Locans Pressured Torso Armor": [
      {
        "uc": 866,
        "y": 3
      }
    ],
    "Locans Stabilized Arm Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "Locans Stabilized Helmet": [
      {
        "uc": 833,
        "y": 3
      }
    ],
    "Locans Stabilized Leg Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "Locans Stabilized Shoulder Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "Locans Stabilized Torso Armor": [
      {
        "uc": 861,
        "y": 3
      }
    ],
    "Metabolic Arm Pads": [
      {
        "uc": 373,
        "y": 3
      }
    ],
    "Metabolic Gloves": [
      {
        "uc": 208,
        "y": 3
      }
    ],
    "Metabolic Helmet": [
      {
        "uc": 833,
        "y": 3
      }
    ],
    "Metabolic Leg Pads": [
      {
        "uc": 373,
        "y": 3
      }
    ],
    "Metabolic Shoulder Pads": [
      {
        "uc": 373,
        "y": 3
      }
    ],
    "Metabolic Torso Armor": [
      {
        "uc": 859,
        "y": 3
      }
    ],
    "metal alloy": [
      {
        "uc": 95,
        "y": 2
      },
      {
        "uc": 95,
        "y": 2
      }
    ],
    "Militek EMP": [
      {
        "uc": 415,
        "y": 5
      },
      {
        "uc": 408,
        "y": 5
      }
    ],
    "MT-27 Ballistics Arm Pads": [
      {
        "uc": 371,
        "y": 3
      }
    ],
    "MT-27 Ballistics Helmet": [
      {
        "uc": 714,
        "y": 3
      }
    ],
    "MT-27 Ballistics Leg Pads": [
      {
        "uc": 371,
        "y": 3
      }
    ],
    "MT-27 Ballistics Shoulder Pads": [
      {
        "uc": 371,
        "y": 3
      }
    ],
    "MT-27 Ballistics Torso Armor": [
      {
        "uc": 740,
        "y": 3
      }
    ],
    "Mystical Cola": [
      {
        "uc": 57,
        "y": 5
      }
    ],
    "Nano Bite Burger": [
      {
        "uc": 64,
        "y": 5
      }
    ],
    "NanoTech Cognizant Arm Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "NanoTech Cognizant Gloves": [
      {
        "uc": 194,
        "y": 3
      }
    ],
    "NanoTech Cognizant Helmet": [
      {
        "uc": 868,
        "y": 3
      }
    ],
    "NanoTech Cognizant Leg Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "NanoTech Cognizant Shoulder Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "NanoTech Cognizant Torso Armor": [
      {
        "uc": 866,
        "y": 3
      }
    ],
    "NanoTech Scout Arm Pads": [
      {
        "uc": 373,
        "y": 3
      }
    ],
    "NanoTech Scout Gloves": [
      {
        "uc": 208,
        "y": 3
      }
    ],
    "NanoTech Scout Helmet": [
      {
        "uc": 833,
        "y": 3
      }
    ],
    "NanoTech Scout Leg Pads": [
      {
        "uc": 373,
        "y": 3
      }
    ],
    "NanoTech Scout Shoulder Pads": [
      {
        "uc": 373,
        "y": 3
      }
    ],
    "NanoTech Scout Torso Armor": [
      {
        "uc": 859,
        "y": 3
      }
    ],
    "NanoTech Trauma Arm Pads": [
      {
        "uc": 377,
        "y": 3
      }
    ],
    "NanoTech Trauma Gloves": [
      {
        "uc": 198,
        "y": 3
      }
    ],
    "NanoTech Trauma Helmet": [
      {
        "uc": 833,
        "y": 3
      }
    ],
    "NanoTech Trauma Leg Pads": [
      {
        "uc": 377,
        "y": 3
      }
    ],
    "NanoTech Trauma Shoulder Pads": [
      {
        "uc": 377,
        "y": 3
      }
    ],
    "NanoTech Trauma Torso Armor": [
      {
        "uc": 859,
        "y": 3
      }
    ],
    "NanoTech Vitality Arm Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "NanoTech Vitality Helmet": [
      {
        "uc": 833,
        "y": 3
      }
    ],
    "NanoTech Vitality Leg Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "NanoTech Vitality Shoulder Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "NanoTech Vitality Torso Armor": [
      {
        "uc": 861,
        "y": 3
      }
    ],
    "NanoTech Voltaic Arm Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "NanoTech Voltaic Gloves": [
      {
        "uc": 197,
        "y": 3
      }
    ],
    "NanoTech Voltaic Helmet": [
      {
        "uc": 860,
        "y": 3
      }
    ],
    "NanoTech Voltaic Leg Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "NanoTech Voltaic Shoulder Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "NanoTech Voltaic Torso Armor": [
      {
        "uc": 861,
        "y": 3
      }
    ],
    "Night Vision Implant": [
      {
        "uc": 2535,
        "y": 1
      }
    ],
    "Orbit XB Energy Cell": [
      {
        "uc": 137,
        "y": 4
      }
    ],
    "Orbit XB Infineon": [
      {
        "uc": 3206,
        "y": 1
      },
      {
        "uc": 3149,
        "y": 1
      },
      {
        "uc": 3217,
        "y": 1
      }
    ],
    "plastic": [
      {
        "uc": 404,
        "y": 1
      }
    ],
    "plastic syntactic foam": [
      {
        "uc": 281,
        "y": 3
      }
    ],
    "Portable Vortex Particle Emitter": [
      {
        "uc": 6506,
        "y": 1
      }
    ],
    "PreMet Buffer Arm Pads": [
      {
        "uc": 377,
        "y": 3
      }
    ],
    "PreMet Buffer Gloves": [
      {
        "uc": 198,
        "y": 3
      }
    ],
    "PreMet Buffer Helmet": [
      {
        "uc": 833,
        "y": 3
      }
    ],
    "PreMet Buffer Leg Pads": [
      {
        "uc": 377,
        "y": 3
      }
    ],
    "PreMet Buffer Shoulder Pads": [
      {
        "uc": 377,
        "y": 3
      }
    ],
    "PreMet Buffer Torso Armor": [
      {
        "uc": 859,
        "y": 3
      }
    ],
    "PreMet Collision Arm Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "PreMet Collision Gloves": [
      {
        "uc": 197,
        "y": 3
      }
    ],
    "PreMet Collision Helmet": [
      {
        "uc": 860,
        "y": 3
      }
    ],
    "PreMet Collision Leg Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "PreMet Collision Shoulder Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "PreMet Collision Torso Armor": [
      {
        "uc": 861,
        "y": 3
      }
    ],
    "PreMet Contact Arm Pads": [
      {
        "uc": 373,
        "y": 3
      }
    ],
    "PreMet Contact Gloves": [
      {
        "uc": 208,
        "y": 3
      }
    ],
    "PreMet Contact Helmet": [
      {
        "uc": 833,
        "y": 3
      }
    ],
    "PreMet Contact Leg Pads": [
      {
        "uc": 373,
        "y": 3
      }
    ],
    "PreMet Contact Shoulder Pads": [
      {
        "uc": 373,
        "y": 3
      }
    ],
    "PreMet Contact Torso Armor": [
      {
        "uc": 859,
        "y": 3
      }
    ],
    "PreMet Helmet": [
      {
        "uc": 833,
        "y": 3
      }
    ],
    "PreMet Impact Arm Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "PreMet Impact Gloves": [
      {
        "uc": 194,
        "y": 3
      }
    ],
    "PreMet Impact Helmet": [
      {
        "uc": 868,
        "y": 3
      }
    ],
    "PreMet Impact Leg Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "PreMet Impact Shoulder Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "PreMet Impact Torso Armor": [
      {
        "uc": 866,
        "y": 3
      }
    ],
    "PreMet Tremor Arm Pads": [
      {
        "uc": 371,
        "y": 3
      }
    ],
    "PreMet Tremor Leg Pads": [
      {
        "uc": 371,
        "y": 3
      }
    ],
    "PreMet Tremor Shoulder Pads": [
      {
        "uc": 371,
        "y": 3
      }
    ],
    "PreMet Tremor Torso Armor": [
      {
        "uc": 866,
        "y": 3
      }
    ],
    "professional electronic": [
      {
        "uc": 833,
        "y": 1
      }
    ],
    "Protonix Barracuda": [
      {
        "uc": 1968,
        "y": 1
      },
      {
        "uc": 1954,
        "y": 1
      }
    ],
    "Pulse Mineral Water": [
      {
        "uc": 43,
        "y": 5
      }
    ],
    "Pythica Durable Battle Arm Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "Pythica Durable Battle Helmet": [
      {
        "uc": 833,
        "y": 3
      }
    ],
    "Pythica Durable Battle Leg Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "Pythica Durable Battle Shoulder Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "Pythica Durable Battle Torso Armor": [
      {
        "uc": 866,
        "y": 3
      }
    ],
    "Pythica Mobile Infantry Arm Pads": [
      {
        "uc": 373,
        "y": 3
      }
    ],
    "Pythica Mobile Infantry Gloves": [
      {
        "uc": 208,
        "y": 3
      }
    ],
    "Pythica Mobile Infantry Helmet": [
      {
        "uc": 833,
        "y": 3
      }
    ],
    "Pythica Mobile Infantry Leg Pads": [
      {
        "uc": 373,
        "y": 3
      }
    ],
    "Pythica Mobile Infantry Shoulder Pads": [
      {
        "uc": 373,
        "y": 3
      }
    ],
    "Pythica Mobile Infantry Torso Armor": [
      {
        "uc": 859,
        "y": 3
      }
    ],
    "Pythica S1 Arm Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "Pythica S1 Gloves": [
      {
        "uc": 197,
        "y": 3
      }
    ],
    "Pythica S1 Helmet": [
      {
        "uc": 860,
        "y": 3
      }
    ],
    "Pythica S1 Leg Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "Pythica S1 Shoulder Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "Pythica S1 Torso Armor": [
      {
        "uc": 861,
        "y": 3
      }
    ],
    "Pythica Special Operations Arm Pads": [
      {
        "uc": 377,
        "y": 3
      }
    ],
    "Pythica Special Operations Gloves": [
      {
        "uc": 198,
        "y": 3
      }
    ],
    "Pythica Special Operations Helmet": [
      {
        "uc": 833,
        "y": 3
      }
    ],
    "Pythica Special Operations Leg Pads": [
      {
        "uc": 377,
        "y": 3
      }
    ],
    "Pythica Special Operations Shoulder Pads": [
      {
        "uc": 377,
        "y": 3
      }
    ],
    "Pythica Special Operations Torso Armor": [
      {
        "uc": 859,
        "y": 3
      }
    ],
    "Pythica Sustained Battle Arm Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "Pythica Sustained Battle Gloves": [
      {
        "uc": 194,
        "y": 3
      }
    ],
    "Pythica Sustained Battle Helmet": [
      {
        "uc": 868,
        "y": 3
      }
    ],
    "Pythica Sustained Battle Leg Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "Pythica Sustained Battle Shoulder Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "Pythica Sustained Battle Torso Armor": [
      {
        "uc": 866,
        "y": 3
      }
    ],
    "Resistance Amp": [
      {
        "uc": 4351,
        "y": 1
      }
    ],
    "RGI-9": [
      {
        "uc": 3150,
        "y": 1
      },
      {
        "uc": 3171,
        "y": 1
      }
    ],
    "rgi-9 rounds": [
      {
        "uc": 61,
        "y": 4
      }
    ],
    "rubber": [
      {
        "uc": 156,
        "y": 1
      }
    ],
    "Ryx 7 Energy Cell": [
      {
        "uc": 71,
        "y": 4
      }
    ],
    "Ryx 7 Streamline": [
      {
        "uc": 1930,
        "y": 1
      },
      {
        "uc": 1910,
        "y": 1
      }
    ],
    "Salvotec HP220": [
      {
        "uc": 499,
        "y": 5
      }
    ],
    "Scanner Implant": [
      {
        "uc": 2535,
        "y": 1
      }
    ],
    "Shield Implant": [
      {
        "uc": 4351,
        "y": 1
      }
    ],
    "Shoulder Lamp": [
      {
        "uc": 1651,
        "y": 1
      },
      {
        "uc": 1617,
        "y": 1
      }
    ],
    "Small MediKit": [
      {
        "uc": 62,
        "y": 3
      }
    ],
    "special steel alloy": [
      {
        "uc": 442,
        "y": 1
      },
      {
        "uc": 442,
        "y": 1
      }
    ],
    "Stamina Amplification": [
      {
        "uc": 4351,
        "y": 1
      }
    ],
    "Standard MediKit": [
      {
        "uc": 88,
        "y": 3
      }
    ],
    "Tactical Systems Arm Pads": [
      {
        "uc": 371,
        "y": 3
      }
    ],
    "Tactical Systems Helmet": [
      {
        "uc": 714,
        "y": 3
      }
    ],
    "Tactical Systems Leg Pads": [
      {
        "uc": 371,
        "y": 3
      }
    ],
    "Tactical Systems Shoulder Pads": [
      {
        "uc": 371,
        "y": 3
      }
    ],
    "Tactical Systems Torso Armor": [
      {
        "uc": 740,
        "y": 3
      }
    ],
    "Target Painter": [
      {
        "uc": 3252,
        "y": 1
      },
      {
        "uc": 3233,
        "y": 1
      }
    ],
    "Techtronic 6x6": [
      {
        "uc": 1938,
        "y": 1
      },
      {
        "uc": 1884,
        "y": 1
      },
      {
        "uc": 1914,
        "y": 1
      }
    ],
    "Techtronic Rounds": [
      {
        "uc": 61,
        "y": 4
      }
    ],
    "textiles": [
      {
        "uc": 79,
        "y": 5
      },
      {
        "uc": 77,
        "y": 5
      }
    ],
    "titanium alloy": [
      {
        "uc": 612,
        "y": 1
      }
    ],
    "titanium syntactic foam": [
      {
        "uc": 420,
        "y": 3
      }
    ],
    "Venom Arm Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "Venom Gloves": [
      {
        "uc": 197,
        "y": 3
      }
    ],
    "Venom Helmet": [
      {
        "uc": 860,
        "y": 3
      }
    ],
    "Venom Leg Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "Venom Shoulder Pads": [
      {
        "uc": 386,
        "y": 3
      }
    ],
    "Venom Torso Armor": [
      {
        "uc": 861,
        "y": 3
      }
    ],
    "XenoTech Expeditionary Arm Pads": [
      {
        "uc": 86,
        "y": 3
      }
    ],
    "XenoTech Expeditionary Gloves": [
      {
        "uc": 99,
        "y": 3
      }
    ],
    "XenoTech Expeditionary Helmet": [
      {
        "uc": 98,
        "y": 3
      }
    ],
    "XenoTech Expeditionary Leg Pads": [
      {
        "uc": 86,
        "y": 3
      }
    ],
    "XenoTech Expeditionary Shoulder Pads": [
      {
        "uc": 86,
        "y": 3
      }
    ],
    "XenoTech Expeditionary Torso Armor": [
      {
        "uc": 160,
        "y": 3
      }
    ],
    "Zanathid 5 Inflex": [
      {
        "uc": 1876,
        "y": 1
      },
      {
        "uc": 1872,
        "y": 1
      }
    ],
    "Zanathid 5 Rounds": [
      {
        "uc": 98,
        "y": 4
      }
    ]
  }
};
